### ISSUE TITLE
Why is `36e8` added to `osm_id`s

### ISSUE THREAD

**Issue by erkanyildiz** [anvaka/city-roads#10]
https://github.com/anvaka/city-roads/blob/64c5867406c1a16621b9db9081e16a743aba4d52/src/components/FindPlace.vue#L141

I see `36e8` is added to `osm_id`s on Nominatim API results. Can you explain the rationale behind this?

**Comment by anvaka** [comment]
That's because we need overpass areas, not osm ids when we query all roads within an area. Relationship between areas and osm id is documented here: https://wiki.openstreetmap.org/wiki/Overpass_API/Overpass_QL#By_area_.28area.29

**Comment by erkanyildiz** [comment]
I see. Thank you very much. 
Should we replace it with a const and add an inline note?

**Comment by anvaka** [comment]
Sounds like a good idea!

**Comment by anvaka** [comment]
This is done now.
