### ISSUE TITLE
[Feature Request] add a resolution option when downloading as png

### ISSUE THREAD

**Issue by kenkangxgwe** [anvaka/city-roads#15]
Hi, I know the image is rendered by the browser, so I am curious if it is possible to render and download as png with an arbitrary resolution? Thanks!

**Comment by piebro** [comment]
You could download the map as an SVG and then use for example inkscape to convert it to png image of any resolution.

**Comment by kenkangxgwe** [comment]
Close. Use #22 as a workaround.
