### ISSUE TITLE
[Feature Request] Add a perspective view

### ISSUE THREAD

**Issue by Donokami** [anvaka/city-roads#17]
It would be really cool if we cool see the lines in a 3d way, a bit like on Google Earth, would be very interesting for renders. Thanks!

**Comment by anvaka** [comment]
This is possible now via console API.  If you type this:

``` js
scene.queryLayer().lines.rotateX(-Math.PI/4)
```

It will add the perspective to the city

![image](https://user-images.githubusercontent.com/225407/75630756-2d3ca480-5ba2-11ea-8f25-7df5e5e8234d.png)

A bit cumbersome admittedly. I'm still trying to crystalize the intuitive UI for all 3d manipulations along with better navigation in 3D

**Comment by anvaka** [comment]
This is now enabled for all. Announcement: https://twitter.com/anvaka/status/1246534725088362496

It supports all input devices that I could test:

### Mouse

Use `Alt` + `Mouse Drag` to change perspective

### Touch

* Two fingers rotation
* Two fingers scale
* Two fingers when moved up at the same time - change perspective

### Keyboard

* standard arrow keys should work
* `W` - move up
* `A` - move left
* `D` - move right
* `S` - move down
* `Q` - rotate left
* `E` - rotate right
* `F` - incline down
* `R` - incline up
* `-` - zoom out
* `=` - zoom in

Please let me know if there are any issues found.
