### ISSUE TITLE
Export as SVG

### ISSUE THREAD

**Issue by vegatones** [anvaka/city-roads#22]
Thank you for making this live :). But it would be great to be able to export it as SVG to get full control when customizing it for any visual design.

**Comment by JacqueH** [comment]
@vegatones do a search and you'll find this has been addressed . . .

**Comment by anvaka** [comment]
@vegatones  you can click "customize" and then export to svg should be visible:

![image](https://user-images.githubusercontent.com/225407/73334077-8078ab80-4220-11ea-9601-038691f39336.png)
