### ISSUE TITLE
PNG export lines color does not match screen color

### ISSUE THREAD

**Issue by dej611** [anvaka/city-roads#25]
I look for a city, say `Milano` in Italy, then customize the style to red `rgb(255, 0, 0)` for lines and white `rgb(255,255,255)`.

This is what I have on the screen:

<img width="648" alt="Screenshot 2020-01-31 at 08 42 57" src="https://user-images.githubusercontent.com/924948/73521342-0e61bb80-4406-11ea-845d-bd6f3ff8637f.png">

now I click on `Customize` -> `As an image (.png)` and a png file is downloaded.
This is how the downloaded file looks:

![2020_01_31T07_39_37_250Z](https://user-images.githubusercontent.com/924948/73521432-39e4a600-4406-11ea-9438-7272096e7729.png)

If I try the SVG file, it works fine with the right color.

### Another try

If I set the background color to black, instead of white, when the exported PNG lines color gets closer to the one on screen:

![2020_01_31T07_48_12_733Z](https://user-images.githubusercontent.com/924948/73521763-21c15680-4407-11ea-8e91-fe9a2fbe1dcc.png)

### Inverting colors

Just out of curiousity I've try to invert all color channels in the downloaded png and lines color get almost right - of course the background goes to black:

<img width="923" alt="Screenshot 2020-01-31 at 08 50 10" src="https://user-images.githubusercontent.com/924948/73521655-dc048e00-4406-11ea-9f12-8daf5e933792.png">

### Platform Details

* MacOS 10.15.2
* Firefox 72.0.2

**Comment by dej611** [comment]
Tried now on latest Chrome, MacOS 10.15.2 and it worked fine.

**Comment by anvaka** [comment]
interesting one! What's your alpha channel for the background color when you export in Firefox?

**Comment by dej611** [comment]
Good point: lines had a default `0.8` alpha color set while background had `1`.
I did manually change the lines `alpha` to `1` and the downloaded PNG is now matching the one on the screen.

**Comment by anvaka** [comment]
Please check now. I've updated a blending function, and colors in FireFox seem to be correct now during save: https://anvaka.github.io/city-roads/

I have also created this playground to reproduce the error:
https://jsbin.com/debuzoziyo/1/edit?js,output

Changing 

```
context.blendFunc(context.SRC_ALPHA, context.ONE_MINUS_SRC_ALPHA);
```

To

```
context.blendFunc(context.DST_ALPHA, context.ONE_MINUS_SRC_ALPHA);
```

fixes the issue.  I'm still learning WebGL, and I hope I'm not missing something else. Please let me know if I do!

**Comment by anvaka** [comment]
Closing. Please let me know if you find any other issue
