### ISSUE TITLE
Cannot find module "w-gl"

### ISSUE THREAD

**Issue by nornagon** [anvaka/city-roads#26]
I get this error when loading the page at https://anvaka.github.io/city-roads:

<img width="440" alt="Draw_all_roads_in_a_city_at_once" src="https://user-images.githubusercontent.com/172800/73598839-dfc10f00-44f1-11ea-9393-24a1dacac2e2.png">

**Comment by anvaka** [comment]
Fixed! Sorry for the inconvenience.

**Comment by nornagon** [comment]
awesome, thanks!
