### ISSUE TITLE
[Discussion] Custom Queries

### ISSUE THREAD

**Issue by piebro** [anvaka/city-roads#27]
I think it would be cool to be able to do custom queries and draw them.

Pro:
 - adding railroads / buildings / water boundaries #19 #13 or other thing to the map or get rid of everything but highways and select a bigger area
 - easy testing in sharing of custom queries with the website
Con:
 - no caching for the custom queries
 - possibly big queries

I guess it shouldn't be to hard to fork this repo and just edit the request and create custom maps but I'm curios what your thoughts are on custom queries.

**Comment by msurguy** [comment]
👍 I wonder what needs to go into that, server side component?

**Comment by anvaka** [comment]
This is coming very soon (probably end of this week - start of the next week)!

The API will be exposed via console first, and once crystalized we will add UI components to allow non-technical users to interact with it.

**Comment by piebro** [comment]
Nice, exposing the API via console first sounds like a great idea. Awesome work!

**Comment by mlcampbe** [comment]
Can you provide a way that we can test the API via the console. What calls/steps would we use to invoke this?

**Comment by anvaka** [comment]
@mlcampbe I've just pushed initial doc here: https://github.com/anvaka/city-roads/blob/master/API.md - please let me know what you think.

**Comment by mlcampbe** [comment]
Anvaka, yes it makes sense and it works but I was hoping to be able to add water boundaries as in request #19. In my small town Roads and RoadStrict don't really do anything and Buildings adds just a few things. But, we have lots of water so was hoping to find a way to add a layer for the water and then color it. Is that coming later or something I'll have to figure out via custom queries?

**Comment by anvaka** [comment]
@mlcampbe I'm still learning overpass query language, so this may not be correct. I saw your weather project, and tested this with the [Decatur coordinates](https://github.com/mlcampbe/weather-forecast-io/blob/d81292a68600ab0d262f8faf84ae6e39d16712e8/weather-forecast-io/index.coffee#L4-L5). 

Try the following query:

``` js
scene.clear(); 

scene.load('', {
  raw: `[out:json][timeout:250];
(
  (
    way[highway](around:7000, {{geocodeCoords:Decatur}}); 
    node(w);
  );
  (
    way[natural='water'](around:7000, {{geocodeCoords:Decatur}});
    node(w);
  );
  (
    way[waterway='river'](around:7000, {{geocodeCoords:Decatur}});
    node(w);
  );
  (
    relation[natural='water'](around:7000, {{geocodeCoords:Decatur}});
    way(r);
    node(w);
  );
);
out skel;`
})
```

This query should fetch all roads along with water-related ways and relationship within 7km of the Decatur center. I explicitly used `around` clause here and not the area id, because some water related places are not part of the  Decatur area.

**Comment by mlcampbe** [comment]
That works but it appears to bring up a different "Decatur" than the one in Alabama. There are about 12 or 13 cities named Decatur so I am not sure which one it got but it was not Alabama!! But, I can now see what the correct format should be and can play around with different geocodeCoords settings to see if I can figure it out or use a bbox area.

**Comment by mlcampbe** [comment]
I was hoping to generate a map very similar to https://i.imgur.com/JuulxyJ.png where the river is the grey color and the major highways are a darker black than the other roads. So far no such luck. Even with the above scene.load... pieces the river is not loading properly. It seems to load as a single line not as all of the grey area in the sample image.

**Comment by mlcampbe** [comment]
I made some progress and determined that the correct tag should likely be waterway=riverbank based on some testing directly inside of openstreetmap. For example I can see https://i.imgur.com/csAz8JZ.png with the outlined orange a portion of the riverbank. However, when trying to load way['waterway'~'riverbank'] from the dev console it shows https://i.imgur.com/vrmIiIh.png. It appears to be a part of the riverbank edge but does not seem to render all of it.
