### ISSUE TITLE
Makes Planting bombs a breez.

### ISSUE THREAD

**Issue by sukhchainn** [anvaka/city-roads#30]
I was thinking about this a few years ago, "How do terrorists plan their terrorist activities?". I got the answer after a bit of a research. Apparently either they have to scout the area and make a map manually or they involve someone who had worked with city council or in some way involved with Municipal Corporation. But they were traditional ways, after seeing so many technical advancements and so many opensource projects like this, which can be used to ease the planning and execution of a bomb blast, I have to reconsider and recompile my research on the subject and ways to prevent such acts.

Anyways, thanks for this beautiful project. 
A quote from my notes as a footnote :- "Act of terrorism is not beautiful, but it's planning is."

**Comment by anvaka** [comment]
Thank you for sharing this perspective!

I hope this tool is not used by terrorists, I'd also kindly ask them to love people instead of killing or harming them
