### ISSUE TITLE
[Feature Request] Add export

### ISSUE THREAD

**Issue by jz222** [anvaka/city-roads#49]
Hi,

thank you for this amazing project. I was wondering if you could make it possible to export the map as SVG or PNG with transparent background.

Thank you!

**Comment by anvaka** [comment]
Just click `Customize` and there should be an option to export as either SVG or PNG: 


![image](https://user-images.githubusercontent.com/225407/123558899-b986b980-d74d-11eb-9347-d2b92dbd38ab.png)

**Comment by jz222** [comment]
Oh, I didn't see that! Thank you!
