### ISSUE TITLE
PNG download not working

### ISSUE THREAD

**Issue by FischerJo** [anvaka/city-roads#5]
Great work so far!

Sadly, the PNG download does not work for me. In particular, when I click "As an image (.png)", a dashed rectangle appears around it - so it seems the click is registered - but nothing happens.

**Comment by anvaka** [comment]
What browser are you using? I noticed similar behavior in the older edge/ie browser, but it was gone after I updated the browser.

**Comment by FischerJo** [comment]
I am using Firefox Version 60.9.0esr (64-bit) under Debian stretch  Release 9.11.

**Comment by anvaka** [comment]
Can you please try now? There was a bug in iOS due to how quickly blob url was released. I fixed the bug, and wonder if it also fixes your use case?

**Comment by FischerJo** [comment]
It indeed works now! Thanks!
