### ISSUE TITLE
[Feature request] Fine grained zooming

### ISSUE THREAD

**Issue by FischerJo** [anvaka/city-roads#6]
Thanks for your work!

If you have some spare time, it would be great if you can add a zoom bar somewhere, as the scrolling by mousewheel can be too coarse from time to time.

**Comment by anvaka** [comment]
Will think about it. In the mean time, would using +/- keys on the keyboard work? Or they are too coarse as well?

**Comment by FischerJo** [comment]
They are too coarse as well. Just some way of making a finer granularity would be good, not necessary a bar clotting the interface. Maybe pressing Shift key while zooming to make it fine-grained?

Thanks for your quick response! Coffee coming soon ;)

**Comment by anvaka** [comment]
:D pushed the update - the `shift` key should now slow down the zooming 10x. Please let me know if this is granular enough

**Comment by FischerJo** [comment]
That is much better :) Thank you!
