### ISSUE TITLE
Danish cities seem unsearchable

### ISSUE THREAD

**Issue by mifriis** [anvaka/city-roads#8]
This is a bit of a niche issue, but of all the countries i tried in Europe they all seem to find cities without any problems.

When i tried Denmark, i couldn't find any. I know you use overpass turbo but openstreet maps do have most if not all danish cities and towns.

I attempted to find the /search?q=town endpoint in your code to dive into the query that gets sent but i can't seem to find it. It could be that data is classified differently here?

All our neighbours like Germany, Norway, UK, Netherlands and Sweden are working just diddly fine.

**Comment by erkanyildiz** [comment]
I see Nominatim API results for Danish cities have`osm_type`s as `node` only.

https://nominatim.openstreetmap.org/search?format=json&q=copenhagen
https://nominatim.openstreetmap.org/search?format=json&q=brondby
https://nominatim.openstreetmap.org/search?format=json&q=aalborg

I do not know why, but results are filtered by `osm_type` as `relation`.

https://github.com/anvaka/city-roads/blob/64c5867406c1a16621b9db9081e16a743aba4d52/src/components/FindPlace.vue#L138

I believe this is the reason.

**Comment by erkanyildiz** [comment]
Related https://github.com/anvaka/city-roads/issues/7

**Comment by mifriis** [comment]
Fixed in 999b941fab4b78ea80b82342b03bdae309ba421b thank you!
