### ISSUE TITLE
Can't use Administrative areas

### ISSUE THREAD

**Issue by KingOfCoders** [anvaka/city-roads#9]
I have tried to do Seliegenstadt, Germany, however it says that it is an "administrative" region. It doesn't work with those apparently.
![image](https://user-images.githubusercontent.com/14859846/72826555-ac9f9580-3c3e-11ea-8db0-5a13713f3998.png)
Also doesn't work with Oster, Ukraine.
![image](https://user-images.githubusercontent.com/14859846/72826512-9b568900-3c3e-11ea-8b9e-ec02a12828dd.png)

**Comment by KingOfCoders** [comment]
Also can't do any of Hesse:
![image](https://user-images.githubusercontent.com/14859846/72826650-da84da00-3c3e-11ea-9061-294ba065b40c.png)

**Comment by KingOfCoders** [comment]
Note: Berlin is an "administrative area" yet it works on here... I'm confused.

**Comment by KingOfCoders** [comment]
Note: Just figured it out, just takes a whole lot of time before it works.

**Comment by anvaka** [comment]
Yes, unfortunately fetching directly from openstreetmap is time consuming and sometimes servers timeout. I'm using three different endpoints to rotate requests when one endpoint fails:

https://github.com/anvaka/city-roads/blob/218d58b698a684b7b333407570744854e094d4e1/src/lib/postData.js#L5

 If anyone has more overpass turbo urls please share

**Comment by tycrek** [comment]
@anvaka Sometimes I get an error `t is null` when doing Administrative areas. Granted, so far I've only seen it on places like California which is understandably HUGE, but Canadian provinces tend to work fine.
